USE BANCO_DIGITAL;

CREATE VIEW VISTA_CLIENTES AS
 SELECT * FROM CLIENTES;

SELECT * FROM VISTA_CLIENTES;

CREATE VIEW VISTA_CUENTA_BANCARIA AS
 SELECT * FROM CUENTA_BANCARIA;

CREATE VIEW VISTA_DATOS_BANCARIOS AS
 SELECT * FROM DATOS_BANCARIOS;

SELECT * FROM DATOS_BANCARIOS;

CREATE VIEW VISTA_SERVICIOS AS 
 SELECT * FROM SERVICIOS;
 
SELECT * FROM SERVICIOS; 